#!/bin/sh

## Instructions
# - Place this file as /usr/local/bin/kdialog
# - Set XDG_CURRENT_DESKTOP=KDE

# To pick a directory in nnn, press Space or Ctrl-J.

## Debugging
#args="$@"
#notify-send "kdialog $args"
#echo "kdialog $args" >> $HOME/kdialog-log

# $1 is the window title
getopenfilename() {
    $TERMINAL -t "$1" -e nnn -p /tmp/fileselect
    path=$(tail -n 1 /tmp/fileselect)
    [ -f $path ] && echo "$path"
    rm /tmp/fileselect
}

getexistingdirectory() {
    $TERMINAL -t "$1" -e nnn -p /tmp/fileselect
    path=$(tail -n 1 /tmp/fileselect)
    [ -d $path ] && echo "$path"
    rm /tmp/fileselect
}

getsavefilename() {
    echo "$(getexistingdirectory "$1")/"$2""
}

version() {
    # impersonate the latest version
    echo "kdialog 21.12.1"
}


## Parse options
for (( i=1; i<=$#; i++ ));
do
    case ${!i} in
    --getopenfilename | --getexistingdirectory | --version )
        # get rid of the leading dashes
        fun=${!i##--}
        ;;
    --getsavefilename )
        fun=${!i##--}
        (( i++ ))
        save_path="${!i}"
        save_file="${save_path##/*/}"
        ;;
    --title )
        (( i++ ))
        title=${!i}
        ;;
    esac
done 2> /dev/null;

title=${title:-nnn-kdialog}

## Epic functional programming trick
if ! [ -z "$fun" ]; then
    echo "$($fun "$title" "$save_file")"
fi
